# Site settings
title: Brickworks
email: makertolentino@gmail.com
description: >
baseurl: "/brickworks" # the subpath of your site, e.g. /blog
url: "http://randytolentino.com" # the base hostname & protocol for your site
twitter_username: techtolentino
github_username:  techtolentino

# Collections
collections:
    sections:
        output: true

# Build settings
markdown: kramdown
